### ISSUE TITLE
2.2.1 Updates to result in contract failure

### ISSUE THREAD

**Issue by epoxmaster** [bittorrent/btfs-dashboard#33]
question

What is the reason for the error in the command line as follows?

2022-09-05T04:03:29.397+0900 [31m net/identify identity/id.go:586 error getting peer record from Identify message: failed to validate envelope: invalid signature or incorror ect domain
2022-09-05T04:20:02.933+0900 [31m net/identify identity/id.go:586 error getting peer record from Identify message: failed to validate envelope: invalid signature or incorror ect domain

==============================================================================

2022-09-04T20:41:10.432+0900	[31mERROR[0m	report-status-contract:	reportstatus/reportstatus.go:275	CheckReportStatus err:execution reverted: reportStatus: Invalid lastNonce<Nonce
2022-09-04T20:51:10.446+0900	[31mERROR[0m	report-status-contract:	reportstatus/reportstatus.go:239	ReportStatus err:execution reverted: reportStatus: Invalid lastNonce<Nonce
2022-09-04T20:51:10.446+0900	[31mERROR[0m	report-status-contract:	reportstatus/reportstatus.go:275	CheckReportStatus err:execution reverted: reportStatus: Invalid lastNonce<Nonce
2022-09-04T21:01:10.332+0900	[31mERROR[0m	report-status-contract:	reportstatus/reportstatus.go:239	ReportStatus err:execution reverted: reportStatus: Invalid lastNonce<Nonce
2022-09-04T21:01:10.332+0900	[31mERROR[0m	report-status-contract:	reportstatus/reportstatus.go:275	CheckReportStatus err:execution reverted: reportStatus: Invalid lastNonce<Nonce
2022-09-04T21:11:10.327+0900	[31mERROR[0m	report-status-contract:	reportstatus/reportstatus.go:239	ReportStatus err:execution reverted: reportStatus: Invalid lastNonce<Nonce
2022-09-04T21:11:10.327+0900	[31mERROR[0m	report-status-contract:	reportstatus/reportstatus.go:275	CheckReportStatus err:execution reverted: reportStatus: Invalid lastNonce<Nonce
2022-09-04T21:21:10.334+0900	[31mERROR[0m	report-status-contract:	reportstatus/reportstatus.go:239	ReportStatus err:execution reverted: reportStatus: Invalid lastNonce<Nonce
2022-09-04T21:21:10.334+0900	[31mERROR[0m	report-status-contract:	reportstatus/reportstatus.go:275	CheckReportStatus err:execution reverted: reportStatus: Invalid lastNonce<Nonce
2022-09-04T21:31:10.248+0900	[31mERROR[0m	report-status-contract:	reportstatus/reportstatus.go:239	ReportStatus err:execution reverted: reportStatus: Invalid lastNonce<Nonce
2022-09-04T21:31:10.248+0900	[31mERROR[0m	report-status-contract:	reportstatus/reportstatus.go:275	CheckReportStatus err:execution reverted: reportStatus: Invalid lastNonce<Nonce

**Comment by epoxmaster** [comment]
It is an additional error symptom.
This error comes out and BTFS stops completely.
It appears to be a symptom involved in libp2p
=======================

btfs.exe : panic: runtime error: slice bounds out of range [:19] with capacity 1
 
goroutine 50798104 [running]:
github.com/libp2p/go-libp2p-pnet.(*pskConn).Read(0xc01cd07bc0, 0xc010b2a2c8, 0x1, 0x1, 0x28aa3410108, 0xc01d097650, 0x2776a80)
	pkg/mod/github.com/libp2p/go-libp2p-pnet@v0.2.0/psk_conn.go:43 +0x24c
github.com/multiformats/go-multistream.(*byteReader).ReadByte(0xc01d097650, 0xc002b3fcd0, 0xd725ce, 0xc002b3fcb0)
	pkg/mod/github.com/multiformats/go-multistream@v0.2.0/multistream.go:460 +0x6a
github.com/multiformats/go-varint.ReadUvarint(0x381e880, 0xc01d097650, 0xc01cd07bc0, 0x0, 0x0)
	pkg/mod/github.com/multiformats/go-varint@v0.0.6/varint.go:80 +0x7e
github.com/multiformats/go-multistream.lpReadBuf(0x28ac8d82e20, 0xc01cd07bc0, 0xc002b3fda0, 0x1a110e5, 0x28ac8d82e20, 0xc01cd07bc0, 0xc004806460)
	pkg/mod/github.com/multiformats/go-multistream@v0.2.0/multistream.go:424 +0x74
github.com/multiformats/go-multistream.ReadNextTokenBytes(0x28ac8d82e20, 0xc01cd07bc0, 0x2776c00, 0x28d46c0, 0x28ac8d82e20, 0x2b153ed, 0x12)
	pkg/mod/github.com/multiformats/go-multistream@v0.2.0/multistream.go:407 +0x45
github.com/multiformats/go-multistream.ReadNextToken(...)
	pkg/mod/github.com/multiformats/go-multistream@v0.2.0/multistream.go:396
github.com/multiformats/go-multistream.readProto(0x2a8b633, 0x6, 0x28ac8d82e20, 0xc01cd07bc0, 0xc01cd07bc0, 0xc01cd07bc0)
	pkg/mod/github.com/multiformats/go-multistream@v0.2.0/client.go:110 +0x46
github.com/multiformats/go-multistream.SelectProtoOrFail(0x2a8b633, 0x6, 0x28ac8d82df0, 0xc01cd07bc0, 0x28ac8d82df0, 0xd7208b)
	pkg/mod/github.com/multiformats/go-multistream@v0.2.0/client.go:32 +0x157
github.com/multiformats/go-multistream.SelectOneOf(0xc001b6e1c0, 0x2, 0x2, 0x28ac8d82df0, 0xc01cd07bc0, 0xc000b66c60, 0xc000b66cf0, 0x0, 0x0)
	pkg/mod/github.com/multiformats/go-multistream@v0.2.0/client.go:57 +0x70
github.com/libp2p/go-conn-security-multistream.(*SSMuxer).selectProto.func1(0xc00ce10840, 0xc00cbc5800, 0xc0000e7c70, 0x387dde0, 0xc01cd07bc0, 0xc00ef9be80, 0xc00ef9bea0)
	pkg/mod/github.com/libp2p/go-conn-security-multistream@v0.2.0/ssms.go:68 +0x1a7
created by github.com/libp2p/go-conn-security-multistream.(*SSMuxer).selectProto
	pkg/mod/github.com/libp2p/go-conn-security-multistream@v0.2.0/ssms.go:63 +0xf1
